### ISSUE TITLE
HttpClientExtras.OAuthClientAuthMessageHandler type missing

### ISSUE THREAD

**Issue by Yurijj** [saldoukhov/HttpClientExtras#1]
I'm trying to use HttpClientExtras library to deal with OAuth1 in my RT application.
I can't find type HttpClientExtras.OAuthClientAuthMessageHandler after installing this library with help of NUGET 
PM> Install-Package HttpClientExtras
or
PM> Install-Package HttpClientExtras.RT

Can you please tell me where I can find this type/class?

**Comment by saldoukhov** [comment]
It was refactored out, see https://github.com/saldoukhov/HttpClientExtras/commit/0c8eaf355df7e86daa6580bdf7d83e0b25ed827e#diff-705707c85680530b64d1d5c75c404b6f

Date: Fri, 15 May 2015 03:56:45 -0700

**Comment by Yurijj** [comment]
One more question:
Method of HttpClientExtras:
public static AuthenticationHeaderValue Sign(HttpMethod method, Uri requestUri, Dictionary<string, string> oauthParams, Dictionary<string, string> requestParams, string consumerSecret, string tokenSecret);

What if I want to get access token and don't have a 'string tokenSecret' parameter value yet?
I keep its value equal just null, but during getting access token will get an error:

request
GET https://some.api.com/v1_1/oauth/token HTTP/1.1

response
HTTP/1.1 400 Bad Request
Content-Type: application/x-www-form-urlencoded;charset=UTF-8

message=Unauthorized.&code=400.0300&cause=Some%20of%20required%20parameters%20%28oauth_token%29%20absent

Do you have any example how to get access token (OAUTH 1.0A Two Legged) using your library?

**Comment by saldoukhov** [comment]
2-legged is a proprietary standard, this is what I was using while being at Intuit:
        public async Task<KeyAndSecret> GetAccessToken(string userName, string password)        {            var cli = new HttpClient();            var request = new HttpRequestMessage(HttpMethod.Get, WebEnv.OAuthHost + "oauth/v1/get_access_token_by_intuit_credentials");            var oauthParams = OAuth.CreateOAuthParams();            oauthParams["oauth_consumer_key"] = OAuthTools.UrlEncodeStrict(_authenticator.ConsumerKey);            oauthParams["xoauth_login_name"] = OAuthTools.UrlEncodeStrict(userName);            oauthParams["xoauth_password"] = OAuthTools.UrlEncodeStrict(password);            oauthParams["xoauth_mode"] = "client_auth";            request.Headers.Authorization = OAuth.Sign(HttpMethod.Get, request.RequestUri,                                                                    oauthParams, new Dictionary<string, string>(),                                                                    _authenticator.ConsumerSecret, null);            var resp = await cli.SendAsync(request);            var respStr = await resp.Content.ReadAsStringAsync();            var ks = ParseKeys(respStr, "oauth_token", "oauth_token_secret");            if (!ks.IsInvalid())            {                SetAccessToken(ks);                return ks;            }            throw new AuthException(ks.Error)            {                IsInvalidLogin = ks.Error == "xoauth_password" || ks.Error == "user_refused",            };        }
Then I would assign key and secret to OAuthProtectedResourceMessageHandler.
Date: Mon, 18 May 2015 02:13:07 -0700
